### ISSUE TITLE
Object of type 'ndarray' is not JSON serializable

### ISSUE THREAD

**Issue by PaulJohny** [madhug-nadig/Machine-Learning-Algorithms-from-Scratch#4]
I'm getting a error on  execution of the file k means clustering .py
Object of type 'ndarray' is not JSON serializable

**Comment by Tudyx** [comment]
replace mpld3.show() by plt.show() at the end of the for loop "for classification in km.classes:"

**Comment by madhug-nadig** [comment]
Fixed!
